apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker pull auctionify.azurecr.io/frontend:ba01a59e67e7608b960e59d4110c460cc67fba66
          ports:
            - containerPort: 80