name: 'App/BuildFrontend'
on:
  workflow_dispatch:  # Manual trigger only
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login to Azure Container Registry'
          run: |
            az login 
            az account set --subscription "665b9990-181c-4de5-a3cf-99714a3f241e"
            az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
            
        - name: 'Build and push image'
          run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
          working-directory: ./frontend    
