on:
  workflow_dispatch:  # Manual trigger only

name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login to Azure Container Registry'
          run: |
            az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
            
        - name: 'Build and push image'
          run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }} .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }} 
          working-directory: ./frontend    
