name: 'Terraform Create'
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.2

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: 'Upload Terraform Plan'
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ./terraform/tfplan

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: dev  # Requires manual approval in GitHub Environments

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.2

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Download Terraform Plan'
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: ./terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
