name: 'Terraform Destroy'
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  terraform-plan-destroy:
    name: 'Terraform Plan Destroy'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform

      - name: 'Terraform Plan Destroy'
        run: terraform plan -destroy 
        working-directory: ./terraform


  terraform-destroy:
    name: 'Terraform Destroy'
    needs: terraform-plan-destroy
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval in GitHub Environments

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform
        
      - name: 'Terraform Destroy'
        run: terraform destroy -auto-approve 
        working-directory: ./terraform
